version: '2.2'
services:
    worker:
        image: "ce26c7971766"
        restart: always
        volumes:
         - /mnt/wres_share:/mnt/wres_share
         - /mnt/wres_secrets:/wres_secrets:ro
        network_mode: "host"
        environment:
         - JAVA_OPTS=-Dwres.broker=***REMOVED***wres-broker${WRES_ENV_SUFFIX}
         - PGPASSFILE=/wres_secrets/.pgpass
        # Worker JVM should have 32m max heap, WRES should have 1628m max heap
        mem_limit: 2048m
