# This workflow deals with commits tagged with vx.x-docker tag
name: Docker_Release

on:
  push:
    tags:
      - "v*.*-docker"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 0

    # Zips the docker related components of the release to store them
    - name: Tar Docker
      run: |
        tar -zcvf wres-${{  github.ref_name }}-src.tar.gz scripts/doc*sh */Dockerfile  .dockerignore .gitignore compose*yml Dockerfile

    # Stores the docker related artifacts for this release
    - name: Create docker-release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar.gz
          compose-entry.yml
          compose-workers.yml
